05월 24일 목요일 : anaconda
===

In [1]:
import numpy as np
import scipy

In [2]:
a = np.array([0,1,2])
a

array([0, 1, 2])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
type(a.dtype)

numpy.dtype

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [12]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = np.zeros((2,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a = np.linspace(2,3,11)
a

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

In [26]:
a * a

array([4.  , 4.41, 4.84, 5.29, 5.76, 6.25, 6.76, 7.29, 7.84, 8.41, 9.  ])

In [27]:
a - a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
1/a

array([0.5       , 0.47619048, 0.45454545, 0.43478261, 0.41666667,
       0.4       , 0.38461538, 0.37037037, 0.35714286, 0.34482759,
       0.33333333])

In [29]:
a**2

array([4.  , 4.41, 4.84, 5.29, 5.76, 6.25, 6.76, 7.29, 7.84, 8.41, 9.  ])

In [37]:
A = np.array([[1, 4, 2, 3, 4, 5],[2, 5, 6, 5, 2, 1]])
B = np.linspace(1,6,6)
B = np.transpose(B)
C = np.array([3.5, 2.4])
D = 2.2 * np.ones((2,6))

np.dot(C,np.dot(3*A-D,B))

1011.1200000000001

In [38]:
A = np.array([[i+11 for i in range(6)],[i+17 for i in range(6)],[i+23 for i in range(6)],[i+29 for i in range(6)]])

In [40]:
A[:2,3:]

array([[14, 15, 16],
       [20, 21, 22]])